site_name: AIOM Documentation
site_description: AIOM - A comprehensive Node.js package for customizing, deploying and managing online behavioral experiments
site_author: Haijiang Yan
site_url: https://aiom.readthedocs.io

repo_name: HaijiangYan/AIOM
repo_url: https://github.com/HaijiangYan/AIOM

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - javascript
    - typescript
    - bash
    - json
    - yaml
  navigation_depth: 3
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  collapse_navigation: false

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quick-start.md
    - Configuration: configuration.md
    - API Reference: api-reference.md
  - Examples:
    - Customization: examples/blockwiseMCMCP.md
    - Templates: examples/template_list.md
  - Other:
    - Contributing: contributing.md
    - Changelog: changelog.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: "Table of Contents"
  - tables
  - fenced_code
  - codehilite:
      guess_lang: false
      use_pygments: true
  - sane_lists
  - smarty
  - wikilinks

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  author: Haijiang Yan
  project: AIOM
  version: 1.0.0
  github_url: https://github.com/HaijiangYan/AIOM
  npm_url: https://www.npmjs.com/package/aiom

# Custom CSS for classic ReadTheDocs styling
extra_css:
  - stylesheets/classic.css