site_name: AIOM Documentation
site_description: AIOM - A comprehensive Node.js package for customizing, deploying and managing online behavioral experiments
site_author: Haijiang Yan
site_url: https://aiom.readthedocs.io

repo_name: HaijiangYan/AIOM
repo_url: https://github.com/HaijiangYan/AIOM

theme: 
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - javascript
    - typescript
    - bash
    - json
    - yaml
    - sql
  navigation_depth: 3

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
    - Configuration: configuration.md
  - API Reference:
    - Overview: api/index.md
    - Core Classes: api/core.md
    - Operations: api/operations.md
    - Utilities: api/utils.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Features: examples/advanced.md
    - Integration Examples: examples/integration.md
  - Guides:
    - Best Practices: guides/best-practices.md
    - Troubleshooting: guides/troubleshooting.md
  - Contributing: contributing.md
  - Changelog: changelog.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - fenced_code
  - codehilite:
      use_pygments: true
      guess_lang: false
  - sane_lists

plugins:
  - search

extra_css:
  - stylesheets/custom.css